---
 - name: Deploy Tomcat
   hosts: web
   become: yes
   tasks:
    - name: Copy WAR file
      copy:
        src: "/var/snap/jenkins/4874/workspace/My03/target/My03.war"
        dest: "/opt/tomcat/webapps/My03.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
       - name: tomcat
         state: restarted
